### ISSUE TITLE
LexML, três poderes e três esferas

### ISSUE THREAD

**Issue by ppKrauss** [dadosgovbr/catalogos-dados-brasil#1]
Conteúdos e dados (metadados) abertos... Como registrar no [CSV do catalogos-dados-brasil](https://github.com/dadosgovbr/catalogos-dados-brasil/blob/master/dados/catalogos.csv)?

O [Projeto LexML](http://projeto.lexml.gov.br/documentacao/destaques-lexml#o-que-lexml) integra instituições dos três poderes: Executivo, Legislativo e Judiciário decidem em consenso as normas técnicas LexML. 

Hoje o acervo de metadados contém principalmente normas estatutárias legislativas (leis, leis orgânicas, estatutos, etc. do Legislativo e portarias, resoluções etc. do Executivo)  e jurídicas (acórdãos) da esfera federal. As esferas estadual e municipal também são contempladas. Proposições normativas (ex. projetos de lei) também fazem parte do acervo. 

Estado atual do acervo (agosto de 2015):
- [Legislação](http://www.lexml.gov.br/busca/search?keyword=&f1-tipoDocumento=Legisla%C3%A7%C3%A3o): ~778mil documentos (256mil federais, 100mil estaduais, 376mil municipais).
-  [Jurisprudência](http://www.lexml.gov.br/busca/search?keyword=&f1-tipoDocumento=Jurisprud%C3%AAncia): 5,3milhões de documentos, predominantemente acórdãos. 
- [Proposições](http://www.lexml.gov.br/busca/search?keyword=&f1-tipoDocumento=Proposi%C3%A7%C3%B5es%C2%A0Legislativas): ~66mil documentos.

Importante, que nenhum outro repositório faz ou garante: para cada um desses ~6 milhões de documentos, há um [identificador único transparente (a URN LEX)](https://pt.wikipedia.org/wiki/Lex_%28URN%29), que garante a persistência (são [endereços eternos](https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator)!) e a interoperabilidade (trata-se de um [padrão ePING](http://eping.governoeletronico.gov.br/#p2s5.1) e da forma mais simples e transparente de se identificar um documento).

**Comment by augusto-herrmann** [comment]
Peter,

o LexML é uma iniciativa excelente tecnicamente, de extrema importância, e que eu mesmo tenho acompanhado há mais de uma década. Mas não sei se ele pode ser considerado um catálogo ou mesmo uma iniciativa de dados abertos. Para tanto, seria necessário, no mínimo, ser possível fazer o download dos metadados dos documentos em um formato estruturado e aberto a partir de uma URL fixa.

Todavia, deixarei esse issue aberto por um tempo e, caso alguém apresente uma argumentação convincente de que faz sentido ele estar na lista, poderemos inclui-lo.

**Comment by ppKrauss** [comment]
Augusto,

Acho que devemos examinar as definições com mais cuidado... Ou podemos começar  por simples analogia, que tal uma comparação? Acredito que possamos afirmar o seguinte:

  *  o *portal LexML* "expõe dados abertos" tal com o CKAN de dados.gov.br o faz.

  *  o *acervo LexML* é um (imenso) *dataset* de metadados, tal como dezenas de *datasets* de metadados no  [dados.gov.br](http://dados.gov.br)  ou [dados.prefeitura.sp.gov.br](http://dados.prefeitura.sp.gov.br/) .

  * o acervo LexML "é um acervo aberto", tal como afirmamos no GODI, em  [index.okfn.org/brazil/legislation](http://index.okfn.org/place/brazil/legislation/).

Se concorda com tais afirmações, então devemos supor que o LexML **pode ser considerado uma iniciativa de dados abertos**... Senão supor que o presente projeto está usando uma definição de "dados abertos" incompatível com as usuais. <br/>NOTA: resta explicitar no [README.md](https://github.com/dadosgovbr/catalogos-dados-brasil/blob/master/README.md) a definição empregada no presente projeto.

------

-----
... A seguir vou me alongar pois essa discussão será útil em outras comunidades onde precisamos debater os padrões PING/LexML no contexto da pergunta "o que é uma iniciativa de dados abertos?"... 

-----

Apenas opinar que julgo o  LexML uma iniciativa de dados abertos, é insuficiente... Para de fato buscarmos consenso, talvez o ponto de partida seja a definição de dados abertos que você tinha em mente. Suponho que seja a oficial do governo federal: http://dados.gov.br/dados-abertos/

Antes porém, cabe um refinamento no que queremos dizer com  "o LexML". Ele é várias coisas ao mesmo tempo, vamos separar com mais clareza:

* **acervo LexML de metadados**: são os dados 100%  abertos que comentamos no [GODI](http://index.okfn.org/place/brazil/legislation/), e mais objetivamente são lembrados [aqui](http://www.lexml.gov.br/desc_acervo.html). Os dados brutos podem ser obtidos em XML.

* **acervo de "dados diretamente fornecidos"** (conteúdos marcados em XML): ainda incipiente,  contém apenas itens do contexto "proposições normativas", e apenas da esfera federal. Podemos ignorar por hora. <br>NOTA: o [SciELO](https://en.wikipedia.org/wiki/SciELO) e o [PubMed Central](https://en.wikipedia.org/wiki/PubMed_Central) são exemplos de *acervos de conteúdo em inteiro teor*, codificados em separatas XML que reproduzem fielmente o conteúdo oficial dos jornais... São consideradas iniciativas de dados abertos relevantes.

* **acervo de "dados distribuídos"** (conteúdos HTML ou PDF apontados pelas URLs dos metadados): tal como na arquitetura do CKAN, as fontes originais não precisam estar armazenadas no seu repositório central... As questões de arquitetura são uma "pegadinha", precisam ser decididas para dar mais nexo à discussão... Podemos ignorar esses dados por hora.

* **portal LexML**: ferramenta que faz o mesmo papel que o CKAN num repositório Web de dados abertos. Tal como o CKAN opera com três APIs princiais: 1 engine de busca; 2 expositor de "ficha catalográfica"  e 3 *URN-resolver* das [URNs LEX](https://www.wikidata.org/wiki/Q6537508), superior ao resolvedor "RESOURCE_ID" pois as URNs LEX são *identificadores transparentes* e o seu *resolver* no LexML é um localizador  [PURL](https://www.wikidata.org/wiki/Q195305).

* **normas LexML**: citadas pelo ePING na sua [tabela 16 da seção 5, “Áreas de Integração”](http://eping.governoeletronico.gov.br/#p2s5), e disponíveis nas [Normas Ténicas LexML do projeto.lexml.gov.br/documentacao](http://projeto.lexml.gov.br/documentacao).  <br/>Elas complementam a infraestrutura do *portal* e dos *metadados LexML*, tendo em vista que são abertas e expressam a semântica dos dados de forma aberta (complementadas inclusive por  esquemas e ontologias XML que são também dados abertos).

Nos dias de hoje, 2016, creio que o mais importante a se considerar como "dados abertos" é o *acervo de metadados LexML* e a infra-estrutura (de busca e resolução URN LEX) que promove o acesso transparente, rápido e não-encriptado a esse acervo. 

PS: tradicionalmente chamamos bancos de metadados e sua representação em "fichas catalográficas" de "catálogos", de maneira que além de ser iniciativa de dado aberto, o LexML pode ser considerado também catálogo de dado aberto (e Lei expressa em HTML como [dado aberto de três estrelas](http://5stardata.info/en/) e o PDF com dado aberto de uma estrela).

----
## verificando na definição das 3 leis
 
Verificando se o *acervo de metadados LexML* com sua infraestrutura, é ou não uma iniciativa de dados abertos, segundo as [definições oficiais](http://dados.gov.br/dados-abertos/) e usando a definição intermediária (nem tão geral nem tão detalhada) dada pelas *"três leis dos dados abertos"*: 

1. *"... pode ser encontrado e indexado na Web..."*: <br/>cada [URN LEX](https://www.wikidata.org/wiki/Q6537508) tem sua [URL](https://www.wikidata.org/wiki/Q42253), inclusive algo esquecido da comunidade de dados abertos, porém fundamental para documentos normativos, que é a durabilidade da URL, as URNs LEX são resolvidas por uma [PURL](https://www.wikidata.org/wiki/Q195305). <br/>NOTA: as diferentes versões dos documentos (PDF oficial, HTML compilado, etc.) são identificadas e oferecidas sem ambiguidade. No [modelo FRBR](https://en.wikipedia.org/wiki/Functional_Requirements_for_Bibliographic_Records)  adotado pelo LexML, tal como no modelo do [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier) ([Indecs Content Model](https://en.wikipedia.org/wiki/Indecs_Content_Model)) e do [ISSN-L](https://en.wikipedia.org/wiki/International_Standard_Serial_Number#Linking_ISSN), não existe o risco de ambiguidade presente no CKAN (que não controla) ou no [ISBN](https://en.wikipedia.org/wiki/International_Standard_Book_Number) (que referencia formato).  

2. *".. aberto e disponível em formato compreensível por máquina"*: <br/>existem diferentes fontes abertas para os metadados dos documentos registrados no LexML, talvez não tão explicitas e divulgadas, mas como afirmamos no GODI, essas fontes existem.

3. Nenhum  dispositivo legal proíbe a sua replicação. <br>O *acervo LexML de  metadados* segue a licença usual dos materiais fornecidos na Web pelo Senado (CC0? ODC-By?), e, *a priori*, devem também respeitar a licença das normas publicadas nos diários oficiais (ex. licença para reproduzir ementas). <br>NOTA: se pensarmos nos "dados distribuídos", que tem origem nas URLs dos metadados, são de fato os documentos contendo leis, portarias,etc. ou fascículos inteiros dos diários oficiais... Conforme lembrado no GODI:  [no Brasil a "licença implícita" das normas](https://github.com/ppKrauss/licenses/blob/master/reports/implied-lex-BR-v1.md) e demais matérias publicadas nos Diários Oficiais, é a [CC0](https://creativecommons.org/publicdomain/zero/1.0/). 


-----

## Conclusão

Minha conclusão  é que o LexML,  do ponto de vista conceitual, devido ao uso das URNs LEX, chega até a ser superior a iniciativas baseadas no CKAN e similares, que não oferecem maiores garantias: para o cidadão comum, e para os "operadores do Direito"  brasileiro (advogados, juízes, escriturários, funcionários nas prefeituras, etc.), é fundamental a *identificação única e transparente*, bem como a confiabilidade e perenidade/persistência dessa identificação.

**Comment by augusto-herrmann** [comment]
Peter,

a sua argumentação foi toda no sentido de afirmar que o LexML são dados abertos - com base na definição que está no Portal Brasileiro de Dados Abertos e com a três leis do David Eaves. Em relação a esse ponto não há o que discutir (exceto quanto à equivalência com a CC0, mas esse assunto para [outra discussão](https://github.com/ppKrauss/licenses/issues/7)). Concordo com isso.

Quanto à questão se o LexML seria uma "iniciativa de dados abertos" ou um "catálogo de dados abertos", é algo que merece uma análise mais aprofundada. Você observou que não consta no README do repositório uma definição explícita do que é um catálogo ou uma iniciativa de dados abertos. Concordo que precisamos trabalhar nisso.

Não consegui encontrar uma definição explícita para o termo "iniciativa de dados abertos". Porém podemos trabalhar como arcabouço de referência os documentos *[Open Government Data Toolkit](http://opendatatoolkit.worldbank.org/en/starting.html)* do Banco Mundial e *[Open Government Data: Towards Empirical Analysis of Open Government Data Initiatives](http://www.oecd-ilibrary.org/governance/open-government-data_5k46bj4f03s7-en)* da OCDE. Seguem algumas afirmativas para reflexão.

Uma iniciativa de dados abertos, em geral, implementa uma política de dados abertos, seja ela explícita em um único documento, dispersa em vários, ou implícita baseada em um conjunto de ações e declarações. Uma iniciativa de dados abertos tem um escopo jurisdicional ou de atuação definido. Uma iniciativa de dados abertos tem ações no sentido de incentivar o consumo dos dados pela sociedade civil e promover o engajamento.

Já um catálogo de dados abertos pode ou não fazer parte de uma iniciativa de dados abertos. É um repositório que contém vários conjuntos de dados e estes, por sua vez contêm um ou mais arquivos que podem ser baixados a partir de URLs específicas.

No caso do LexML, a questão dos documentos não serem estruturados, apenas os metadados, mencionada por você, é de fato relevante. Contudo, a deixemos de lado por um instante.

O que há é um webservice que fornece acesso a todos esses metadados como um todo. Parece-me ser mais assemelhado a um conjunto de dados (dataset) (e de fato é tratado dessa forma no [catálogo de dados abertos do Senado](http://dadosabertos.senado.gov.br/dataset/api-search-and-retrieve-via-url-sru)), e não a um catálogo ou uma iniciativa de dados abertos.

Além disso, quando se diz que algo é um *catálogo de dados abertos*, as pessoas têm a expectativa de que poderão realizar uma busca textual e/ou por outros parâmetros e, quando encontrar o que procuram, conseguirão baixar arquivos de dados abertos. Essa expectativa não se satisfaz com o LexML. De fato ele tem uma busca facetada, e os metadados aparecem no resultado. No entanto, a partir desse resultado da busca, não fornece um link para baixar esses mesmos metadados em formato estruturado. Em vez disso, o cidadão precisa consultar a documentação e fazer a consulta no webservice de uma forma totalmente separada da interface principal. Nem mesmo há qualquer link no portal para o webservice, e o cidadão que procura dados abertos, ao acessar o portal, pode mesmo pensar que o LexML não tem dados abertos.

Esses são os motivos que me fazem pensar que o LexML, apesar de ter dados abertos disponíveis, não se qualifica nem como uma iniciativa, nem como um catálogo de dados abertos.

**Comment by ppKrauss** [comment]
Augusto,

Obrigado pelas colocações.  Acho que as conclusões finais desta discussão florescerão naturalmente a partir da definição dos objetivos do projeto, conceituando com um pouco mais de detalhe o que é "catálogo", "metadado", etc. ... Ver issue #4.

Outra opção seria rascunhar os conceitos (e exemplos) na [Wiki deste projeto](https://github.com/dadosgovbr/catalogos-dados-brasil/wiki)... O que acha?

**Comment by augusto-herrmann** [comment]
Concordo. Vamos trabalhar essa questão no texto do README, como sugerido no #4.
