### ISSUE TITLE
Padronização da Planilha

### ISSUE THREAD

**Issue by endersonmenezes** [dadosgovbr/catalogos-dados-brasil#11]
Sou estudante de Engenharia de Software e estou estudando dados abertos em vários contextos, estava a observar o arquivo: https://github.com/dadosgovbr/catalogos-dados-brasil/blob/master/dados/catalogos.csv

Penso que poderíamos padronizar o arquivo com uma coluna a mais envolvendo o UF e até o Município?

Estou brincando um pouco com [CNEP](http://dados.gov.br/dataset/cnep), poderia adicionar ele a planilha?

**Comment by augusto-herrmann** [comment]
Olá, @endersonmenezes.

> Penso que poderíamos padronizar o arquivo com uma coluna a mais envolvendo o UF e até o Município?

Essas colunas sempre estiveram presentes na planilha, como você pode ver se fizer o download da mesma. Na interface do Github, é necessário fazer scroll horizontal para visualizá-las.

> Estou brincando um pouco com CNEP, poderia adicionar ele a planilha?

O CNEP não é um catálogo de dados, e sim um conjunto de dados. Ele está presente no Portal Brasileiro de Dados Abertos, do Poder Executivo Federal.

No arquivo README.md está explicado que o escopo deste repositório são catálogos, portais ou iniciativas de dados abertos de nível mais alto (ex.: o portal de dados abertos da prefeitura do município X, o portal de dados abertos da assembleia legislativa do estado Y, etc.).

**Comment by endersonmenezes** [comment]
@augusto-herrmann desculpa pela falta de atenção, vou estudar melhor e pretendo colaborar com o possível! 
Obrigado pela disponibilidade em responder :)

**Comment by augusto-herrmann** [comment]
Sem problema! :+1:
