### ISSUE TITLE
dados.gov.br fora do ar

### ISSUE THREAD

**Issue by jgt-josegeraldo** [dadosgovbr/catalogos-dados-brasil#13]
Tentei várias vezes acessar o http://dados.gov.br/ incluido de dispositivos e redes diferentes, mas sem sucesso.
Isso é um insponibilidade momentânea ou o algo permanente?
Caso permante teria algum outro lugar onde eu consiga ter acessos a essas informações?

**Comment by augusto-herrmann** [comment]
Este repositório serve apenas para a manutenção da lista de iniciativas de dados abertos de entes públicos brasileiros, :ok: ? Para problemas com o portal, utilizem o e-mail contato@dados.gov.br.

Os responsáveis pelo portal, normalmente, nem ficam sabendo o que é postado aqui.
