### ISSUE TITLE
Link quebrado para Cadastro Nacional de Empresas Inidoneas e Suspensas

### ISSUE THREAD

**Issue by prcastro** [dadosgovbr/catalogos-dados-brasil#3]
Link quebrado neste dataset:

http://dados.gov.br/dataset/cadastro-nacional-de-empresas-inidoneas-e-suspensas

Não sabia onde abrir esse Bug report, então abri aqui.

**Comment by augusto-herrmann** [comment]
Obrigado por nos avisar. O problema foi corrigido.
Entretanto, o meio de contato apropriado para relatar problemas com o portal está descrito na [página de contato](http://dados.gov.br/contato/) do portal dados.gov.br.

Estou fechando o ticket que não tem relação com esse repositório.
