### ISSUE TITLE
README com as definições de dados abertos e de catálogo, adotadas no projeto 

### ISSUE THREAD

**Issue by ppKrauss** [dadosgovbr/catalogos-dados-brasil#4]
Explicitar no [README.md](https://github.com/dadosgovbr/catalogos-dados-brasil/blob/master/README.md) as definições empregadas.

Conforme andamento da discussão em #1 (a partir [deste post](https://github.com/dadosgovbr/catalogos-dados-brasil/issues/1#issuecomment-219299272)) notou-se a relevância dessa demanda.

Também importante fazer distinção de "dado" (ex. XML com tabela e metadado com texto descritivo) e "conteúdo estruturado" (ex. texto descritivo com tabela em XHTML) caso esteja sendo feita essa distinção,  ... E a distinção entre _metadados_ (os dados de fato de um catálogo, que podem ou não ser abertos) e _dados_, bem como entre "dados do catálogo" e "dados revelados pelo catálogo".

---

Sugestões aventadas:
- Definição de _dados abertos_:  "os 8 princípios" reproduzidos na conceituação adotada pelo governo federal, em http://dados.gov.br/dados-abertos/
  - Avaliação de "iniciativa de dados abertos": podemos trabalhar como arcabouço de referência os documentos  [Open Government Data Toolkit](http://opendatatoolkit.worldbank.org/en/starting.html) do Banco Mundial e [Open Government Data](http://www.oecd-ilibrary.org/governance/open-government-data_5k46bj4f03s7-en).
- ... outras defininições ...
- Definição de "catálogo de dados abertos": ....

**Comment by augusto-herrmann** [comment]
Acho que a questão agora está mais clara no README. Caso tenha alguma sugestão de alteração, pode fazê-la diretamente no texto, ok?
