### ISSUE TITLE
Link quebrado no readme.md

### ISSUE THREAD

**Issue by fcatae** [dadosgovbr/catalogos-dados-brasil#8]
Problema simples: o link do readme está quebrado. Acredito que o correto deveria ser:
https://github.com/dadosgovbr/catalogos-dados-brasil/blob/master/dados/catalogos.csv

**Comment by augusto-herrmann** [comment]
Obrigado pelo aviso.

[Corrigido](/dadosgovbr/catalogos-dados-brasil/commit/6a1e97ba77f9aa432e0833da5234596527c53cc9#diff-04c6e90faac2675aa89e2176d2eec7d8)!
